### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by Martin-Hausleitner** [chunggjo/pro-polls#1]
![image](https://user-images.githubusercontent.com/55828102/80708601-40a9b480-8aec-11ea-8e6f-8225ad7f6731.png)

**Comment by chunggjo** [comment]
You need to create a folder called "config", with the file "dev.env" which includes the lines from step #5 in the Readme under "Steps to run".

**Comment by Martin-Hausleitner** [comment]
i allreay done this

**Comment by chunggjo** [comment]
Ok I will look into this

**Comment by chunggjo** [comment]
I have recreated this exact same error after deleting my dev.env file. You need to have the dev.env file after creating the config folder. I will even attach a copy with this, just run "npm install" and then "npm run dev".
[pro-polls.zip](https://github.com/chunggjo/pro-polls/files/4559207/pro-polls.zip)

**Comment by Martin-Hausleitner** [comment]
![image](https://user-images.githubusercontent.com/55828102/80806789-e546f780-8bbb-11ea-878e-0079a3ea2f1a.png)
mhh same error with your zip file

**Comment by chunggjo** [comment]
Did you run npm install? It is telling you that the node_modules folder is missing

**Comment by Martin-Hausleitner** [comment]
now it works
